name: End to End UI automation for Orange Hrm

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to run test on"
        required: true
        type: choice
        default: dev
        options:
          - dev
          - sit
      suite:
        description: "Suite to run"
        required: true
        type: string

jobs:
  UI-Test:
    name: Run UI Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
          CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" \
          | jq -r --arg ver "$CHROME_VERSION" '.channels.Stable.version')
          wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
      - name: Run UI E2E Test
        run: mvn mvn test -P${{inputs.env}} -Dsuite=${{inputs.suite}}
      - name: Set up Allure commandline
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Allure CLI
        run: |
          pip install allure-pytest
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
          tar -xvzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Build and run tests with Allure
        run: mvn clean test

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
            name: allure-report
            path: target/allure-report


